// Task-based groups, independent of seed order. Only published URLs are exposed.
export const articleJourneys: string[][] = [
  ["forms-create-registration", "forms-question-types", "forms-file-upload", "forms-sections-routing", "forms-response-validation"],
  ["forms-create-quiz", "forms-publish-share", "forms-manage-responses", "forms-responses-sheets", "forms-submit-errors"],
  ["slides-create-outline", "slides-theme-layout", "slides-arrange-objects", "slides-images-video", "slides-linked-chart", "slides-animation"],
  ["slides-presenter-notes", "slides-captions", "slides-audience-qa", "slides-print-notes"],
  ["sheets-sort-filter", "sheets-clean-import", "sheets-freeze", "sheets-number-format", "sheets-locale"],
  ["sheets-dropdown", "sheets-checkbox", "sheets-protect", "sheets-print", "sheets-chart", "sheets-conditional-format"],
  ["docs-pages-mode", "docs-page-setup", "docs-word-count", "docs-headings-toc", "docs-page-elements"],
  ["docs-suggestions", "docs-comments", "docs-english-proofread", "docs-translate"],

  ["windows-cleanup", "windows-zip", "windows-nearby-share"],
  ["windows-clipboard", "windows-screen-capture", "windows-default-apps"],
  ["windows-snap", "windows-desktops", "windows-startup-apps", "windows-text-size"],

  ["chrome-update-check", "chrome-crash-diagnosis", "chrome-cache-site-data", "chrome-reset-settings", "chrome-default-search"],
  ["chrome-bookmarks-transfer", "chrome-separate-profiles", "chrome-guest-session"],
  ["chrome-download-errors", "chrome-translate-arabic"],
  ["old-rent-housing-eligibility", "old-rent-housing-documents", "old-rent-housing-apply", "old-rent-housing-post-office", "old-rent-housing-track"],
  ["ration-data-update", "ration-family-join", "ration-card-replacement", "ration-card-governorate-transfer", "ration-card-activation"],
  ["national-id-lost-replacement", "national-id-damaged-replacement", "automated-birth-certificate", "automated-death-certificate", "automated-marriage-certificate"],
  ["vehicle-violations-inquiry", "vehicle-license-renewal-online", "vehicle-license-lost-replacement", "vehicle-license-damaged-replacement", "driving-license-lost-replacement"],
  ["google-backup-codes", "google-device-sessions", "gmail-phishing-report", "chrome-unwanted-notifications"],
  ["drive-safe-sharing", "drive-file-restore", "google-data-download", "gmail-filters"],
  ["android-backup-check", "google-photos-free-device-space", "android-usb-file-transfer", "android-new-phone-transfer", "android-restore-contacts", "android-factory-reset-safe"],
  ["android-app-permissions", "android-privacy-dashboard", "android-location-permissions", "lost-android-find-hub"],
  ["iphone-backup-choice", "lost-iphone-find-my"],
  ["electricity-bill-inquiry", "south-delta-electricity", "north-delta-electricity", "north-cairo-electricity", "south-cairo-electricity", "alexandria-electricity", "upper-egypt-electricity", "beheira-electricity"],
  ["insurance-number-inquiry", "insurance-last-period", "insurance-periods-wages", "insurance-deductions-inquiry", "insurance-purchase-duration"],
  ["pension-payment-inquiry", "beneficiary-pensions-inquiry"],
  ["e-invoice-self-registration", "e-invoice-digital-signature", "e-invoice-gs1-egs-codes", "e-invoice-registration-errors", "e-receipt-readiness"],
  ["takaful-karama-eligibility", "takaful-karama-apply-documents", "takaful-karama-inquiry-complaint"],
  ["birth-certificate-abroad", "national-id-renewal-abroad", "criminal-record-abroad", "consular-document-attestation", "consular-power-of-attorney", "newborn-passport-abroad", "newborn-travel-document", "work-permit-abroad", "foreign-nationality-permission", "marriage-no-objection-certificate", "egyptian-nationality-foreign-wife", "palestinian-egyptian-travel-document", "foreign-marriage-ratification", "marriage-at-egyptian-mission", "divorce-at-egyptian-mission"],
];
