export type GuideIllustration = { src: string; alt: string; caption: string; sourceUrl: string; step: number; updatedAt?: string };
export const guideIllustrations: Record<string, GuideIllustration> = {
  "chrome-cache-site-data": {"src": "/images/diagrams/chrome-cache-choice.webp", "alt": "الكاش يجدد أجزاء الصفحة؛ بيانات الموقع تؤثر في الدخول؛ السجل فئة مختلفة", "caption": "اختر أقل إجراء يطابق مشكلتك. راجع الفئات قبل التأكيد، ولا تحذف كل البيانات تلقائيًا.", "sourceUrl": "https://support.google.com/chrome/answer/95647?hl=en", "step": 2, "updatedAt": "2026-10-01T09:01:00+03:00"},
  "chrome-bookmarks-transfer": {"src": "/images/diagrams/chrome-bookmarks-check.webp", "alt": "تصدير إشارات إلى HTML ثم نقل الملف واستيراده وفحص روابط مختارة", "caption": "الرسم يلخص نقل الإشارات فقط؛ لا يصور واجهة رسمية ولا يعد نسخة كلمات مرور.", "sourceUrl": "https://support.google.com/chrome/answer/96816?hl=en", "step": 2, "updatedAt": "2026-10-01T09:01:00+03:00"},
  "chrome-download-errors": {"src": "/images/diagrams/chrome-download-map.webp", "alt": "الشبكة ثم المساحة ثم إذن الحفظ أو إذن الخادم: أنواع مستقلة لأخطاء التنزيل", "caption": "اقرأ رسالة الخطأ لتختار مسار الفحص. تعديل مجلد التنزيل لا يمنحك إذن الوصول من الخادم.", "sourceUrl": "https://support.google.com/chrome/answer/2898334?hl=en", "step": 1, "updatedAt": "2026-10-01T09:01:00+03:00"},
  "chrome-guest-session": {"src": "/images/diagrams/chrome-guest-limits.webp", "alt": "مقارنة محو سجل جلسة الضيف المحلي ببقاء النشاط مرئيًا للمواقع والشبكة", "caption": "منع الحفظ المحلي لا يساوي إخفاء الهوية. راجع التنزيلات التي حفظتها منفصلة.", "sourceUrl": "https://support.google.com/chrome/answer/6130773?hl=en", "step": 4, "updatedAt": "2026-10-01T09:01:00+03:00"},
  "android-backup-check": { src: "/images/diagrams/android-backup-map.webp", alt: "أربعة مسارات فحص: نسخة الجهاز والصور والملفات المحلية وبيانات التطبيقات", caption: "مثال عملي: ظهور صورك في السحابة لا يثبت نسخ ملفات التنزيلات أو بيانات جميع التطبيقات. افحص المسارات الأربعة قبل مسح الهاتف.", sourceUrl: "https://support.google.com/android/answer/2819582?hl=ar", step: 1 },
  "google-photos-free-device-space": { src: "/images/diagrams/photos-space-choice.webp", alt: "مقارنة إخلاء مساحة الهاتف بحذف الصور من Google Photos مع فحص النسخ أولًا", caption: "اختر الإجراء بحسب هدفك: تحرير ذاكرة الهاتف يختلف عن حذف الصورة من مكتبة حسابك. الرسم يلخص الفرق ولا يمثل أزرار التطبيق.", sourceUrl: "https://support.google.com/photos/answer/6128843?hl=ar", step: 1 },
  "android-usb-file-transfer": { src: "/images/diagrams/usb-transfer-check.webp", alt: "مسار نقل الملفات عبر USB من الكابل وقفل الهاتف حتى فتح الملف على الكمبيوتر", caption: "علامة النجاح هي فتح النسخة على الكمبيوتر. اتصال الكابل وحده لا يثبت أن الملف نُقل.", sourceUrl: "https://support.google.com/android/answer/9064445?hl=ar", step: 1 },
  "android-factory-reset-safe": { src: "/images/diagrams/reset-safety-check.webp", alt: "فحص الحساب والنسخة والشحن وتعليمات الشركة قبل إعادة ضبط Android", caption: "إذا لم تعرف كلمة مرور الحساب أو لم تتحقق من نسخة ملف مهم، توقف قبل التأكيد النهائي. إعادة الضبط تمحو البيانات المحلية.", sourceUrl: "https://support.google.com/android/answer/6088915?hl=ar", step: 1 },
  "android-app-permissions": { src: "/images/diagrams/permissions-review.webp", alt: "مراجعة نوع إذن التطبيق وحاجته وتغيير الخيار ثم اختبار الوظيفة", caption: "مثال: قد لا يعمل مسح رمز QR بعد منع الكاميرا. راجع حاجة الوظيفة بدل منح جميع الأذونات تلقائيًا.", sourceUrl: "https://support.google.com/android/answer/9431959?hl=ar", step: 1 },
};
