// Explicit service-first search titles; 2026 describes this edition, not a new source review.
// Keep full descriptive H1s and factual Article headlines.
export const searchTitles: Record<string, string> = {
  "forms-create-registration": "نموذج تسجيل 2026: إنشاؤه في Google Forms بوضوح",
  "forms-question-types": "أنواع الأسئلة 2026: اختيار المناسب في Google Forms",
  "forms-file-upload": "رفع الملفات 2026: إعداده في Google Forms بأمان",
  "forms-sections-routing": "توجيه الأسئلة 2026: ضبط الأقسام في Google Forms",
  "forms-response-validation": "التحقق من الإجابات 2026: ضبط شروط Google Forms",
  "forms-create-quiz": "اختبار إلكتروني 2026: إنشاؤه وتصحيحه في Google Forms",
  "forms-publish-share": "نشر نموذج 2026: مشاركة رابط Google Forms الصحيح",
  "forms-manage-responses": "ردود النماذج 2026: إدارتها في Google Forms بأمان",
  "forms-responses-sheets": "ردود Google Forms 2026: حفظها في جدول Sheets",
  "forms-submit-errors": "أخطاء النماذج 2026: حل تعذر إرسال Google Forms",
  "slides-create-outline": "عرض تقديمي 2026: إنشاؤه في Google Slides بوضوح",
  "slides-theme-layout": "تصميم الشرائح 2026: توحيد نسق Google Slides",
  "slides-arrange-objects": "عناصر الشرائح 2026: محاذاتها في Google Slides",
  "slides-images-video": "صور وفيديو الشرائح 2026: إضافتها في Google Slides",
  "slides-linked-chart": "مخطط مرتبط 2026: ربط Google Sheets بعرض Slides",
  "slides-animation": "حركة الشرائح 2026: ضبط الانتقالات في Google Slides",
  "slides-presenter-notes": "ملاحظات المتحدث 2026: عرضها مع Google Slides",
  "slides-captions": "ترجمة مباشرة 2026: تشغيلها في عرض Google Slides",
  "slides-audience-qa": "أسئلة الجمهور 2026: تشغيلها في Google Slides",
  "slides-print-notes": "طباعة الشرائح 2026: حفظ ملاحظات Google Slides",
  "sheets-sort-filter": "فرز البيانات 2026: تصفية Google Sheets دون خلط",
  "sheets-clean-import": "تنظيف البيانات 2026: مراجعتها في Google Sheets",
  "sheets-freeze": "تثبيت العناوين 2026: ضبط صفوف Google Sheets",
  "sheets-dropdown": "قائمة منسدلة 2026: ضبط قيمها في Google Sheets",
  "sheets-checkbox": "مربعات الاختيار 2026: تنظيم مهام Google Sheets",
  "sheets-number-format": "تنسيق الأرقام 2026: ضبط التواريخ في Google Sheets",
  "sheets-locale": "إعدادات الموقع 2026: ضبط توقيت Google Sheets",
  "sheets-protect": "حماية الخلايا 2026: منع أخطاء تعديل Google Sheets",
  "sheets-print": "طباعة الجداول 2026: تحديد نطاق Google Sheets",
  "sheets-chart": "رسم بياني 2026: إنشاؤه من بيانات Google Sheets",
  "sheets-conditional-format": "تنسيق شرطي 2026: إضافة تنبيه في Google Sheets",
  "docs-pages-mode": "وضع الصفحات 2026: اختياره في Google Docs بوضوح",
  "docs-page-setup": "هوامش الصفحة 2026: ضبط اتجاه مستند Google Docs",
  "docs-word-count": "عدد الكلمات 2026: حسابه في Google Docs وحدوده",
  "docs-headings-toc": "فهرس المستند 2026: ضبط عناوين Google Docs بوضوح",
  "docs-page-elements": "ترقيم الصفحات 2026: إضافة رأس وحواشي Google Docs",
  "docs-suggestions": "اقتراح تعديلات 2026: مراجعتها في Google Docs",
  "docs-comments": "تعليقات المستند 2026: تنظيم مراجعة Google Docs",
  "docs-english-proofread": "تدقيق الإنجليزية 2026: مراجعة مستند Google Docs",
  "docs-translate": "ترجمة المستند 2026: مراجعة نسخة Google Docs",
  "windows-clipboard": "سجل الحافظة 2026: النسخ والمحو في Windows 11",
  "windows-screen-capture": "لقطة شاشة 2026: القص والحفظ في Windows 11 بوضوح",
  "windows-cleanup": "مساحة الجهاز 2026: تحريرها في Windows 11 بأمان",
  "windows-nearby-share": "مشاركة قريبة 2026: نقل ملفات بين كمبيوترين بأمان",
  "windows-zip": "ملفات ZIP 2026: ضغطها وفكها في Windows 11 بأمان",
  "windows-snap": "تقسيم الشاشة 2026: تنظيم نوافذ Windows 11 بوضوح",
  "windows-desktops": "أسطح المكتب 2026: تنظيم مهام Windows 11 بوضوح",
  "windows-startup-apps": "بدء التشغيل 2026: إدارة تطبيقات Windows 11",
  "windows-text-size": "تكبير النص 2026: ضبط حجمه في Windows 11 بوضوح",
  "windows-default-apps": "التطبيق الافتراضي 2026: تغييره في Windows 11",
  "chrome-update-check": "تحديث Chrome 2026: فحص النسخة وحل تعثر التحديث",
  "chrome-cache-site-data": "كاش Chrome 2026: مسح بيانات الموقع والتحقق بأمان",
  "chrome-reset-settings": "إعدادات Chrome 2026: إعادة ضبطها وفحص النتيجة",
  "chrome-bookmarks-transfer": "إشارات Chrome 2026: تصديرها واستيرادها بأمان",
  "chrome-default-search": "بحث Chrome 2026: تغيير المحرك وفحص الإعدادات",
  "chrome-download-errors": "تنزيلات Chrome 2026: حل الأخطاء بحسب الرسالة",
  "chrome-crash-diagnosis": "تعطل Chrome 2026: تشخيص عدم الفتح وحل المشكلة",
  "chrome-translate-arabic": "ترجمة Chrome 2026: عرض العربية وحل غياب الخيار",
  "chrome-separate-profiles": "ملفات Chrome 2026: فصل حسابات العمل والدراسة",
  "chrome-guest-session": "ضيف Chrome 2026: استخدام مؤقت وحدود الخصوصية",
  "android-backup-check": "نسخ Android 2026: التحقق من اكتمال النسخة بأمان",
  "lost-android-find-hub": "هاتف Android مفقود 2026: العثور عليه وتأمينه",
  "android-app-permissions": "أذونات Android 2026: مراجعة وصول التطبيقات بأمان",
  "google-photos-free-device-space": "مساحة الهاتف 2026: تفريغها عبر Google Photos بأمان",
  "android-new-phone-transfer": "هاتف Android جديد 2026: نقل البيانات والتحقق منها",
  "android-restore-contacts": "جهات اتصال Android 2026: استعادتها من النسخة",
  "android-privacy-dashboard": "خصوصية Android 2026: مراجعة وصول التطبيقات",
  "android-usb-file-transfer": "ملفات Android 2026: نقلها بكابل USB وحل التعثر",
  "android-location-permissions": "موقع Android 2026: اختيار دقة الإذن لكل تطبيق",
  "android-factory-reset-safe": "ضبط Android 2026: مسح الهاتف بعد فحص النسخة",
  "national-id-lost-replacement": "بدل فاقد الرقم القومي 2026: الطلب من مصر الرقمية",
  "national-id-damaged-replacement": "بدل تالف الرقم القومي 2026: الطلب ومراجعة البيانات",
  "automated-death-certificate": "شهادة وفاة مميكنة 2026: طلب نسخة مطبوعة مسبقًا",
  "automated-marriage-certificate": "قسيمة زواج مميكنة 2026: طلب نسخة مطبوعة مسبقًا",
  "ration-data-update": "بيانات التموين 2026: تحديثها عبر مصر الرقمية",
  "ration-family-join": "ضم الأسرة للتموين 2026: الشروط وخطوات الطلب",
  "ration-card-replacement": "بدل بطاقة التموين 2026: الإيقاف وطلب فاقد وتالف",
  "ration-card-governorate-transfer": "نقل بطاقة التموين 2026: الطلب بين المحافظات",
  "ration-card-activation": "تفعيل بطاقة التموين 2026: الشروط وخطوات المتابعة",
  "old-rent-housing-apply": "الإيجار القديم 2026: طلب السكن البديل قبل 12 أكتوبر",
  "old-rent-housing-eligibility": "السكن البديل 2026: مراجعة شروط أهلية الطلب",
  "old-rent-housing-documents": "السكن البديل 2026: تجهيز مستندات الإيجار والدخل",
  "old-rent-housing-post-office": "السكن البديل 2026: التقديم بمساعدة مكتب البريد",
  "old-rent-housing-track": "السكن البديل 2026: متابعة النواقص والتظلم من الرفض",
  "gmail-filters": "فلاتر Gmail 2026: تنظيم الرسائل دون فقد المهم",
  "google-backup-codes": "رموز Google الاحتياطية 2026: إعدادها للتحقق بأمان",
  "google-data-download": "بيانات Google 2026: تنزيلها عبر Takeout بأمان",
  "chrome-unwanted-notifications": "إشعارات Chrome 2026: إيقاف النوافذ المزعجة بأمان",
  "drive-safe-sharing": "مشاركة Google Drive 2026: ضبط الوصول للملف بأمان",
  "drive-file-restore": "ملفات Google Drive 2026: استعادة المحذوف وحدوده",
  "google-device-sessions": "أجهزة Google 2026: مراجعتها وإخراج جهاز غريب",
  "gmail-phishing-report": "تصيّد Gmail 2026: فحص رسالة مشبوهة والإبلاغ عنها",
  "iphone-backup-choice": "نسخ iPhone 2026: اختيار iCloud أو الكمبيوتر",
  "lost-iphone-find-my": "فقدان iPhone 2026: العثور عليه وتجنب رسائل النصب",
  "south-cairo-electricity": "كهرباء جنوب القاهرة 2026: السداد وطرق الشكوى",
  "north-delta-electricity": "كهرباء شمال الدلتا 2026: الفاتورة وقراءة العداد",
  "alexandria-electricity": "كهرباء الإسكندرية 2026: الفاتورة وبلاغات الأعطال",
  "south-delta-electricity": "كهرباء جنوب الدلتا 2026: الاستعلام وسداد الفاتورة",
  "north-cairo-electricity": "كهرباء شمال القاهرة 2026: الفاتورة وقراءة العداد",
  "vehicle-license-renewal-online": "رخصة المركبة 2026: التجديد أونلاين وشروط الطلب",
  "vehicle-license-lost-replacement": "بدل فاقد رخصة المركبة 2026: الطلب والشروط بمصر",
  "vehicle-license-damaged-replacement": "بدل تالف رخصة المركبة 2026: الطلب من مصر الرقمية",
  "vehicle-violations-inquiry": "مخالفات المركبة 2026: الاستعلام عن الرخصة بمصر",
  "driving-license-lost-replacement": "بدل فاقد رخصة القيادة 2026: الشروط وخطوات الطلب",
  "automated-birth-certificate": "شهادة الميلاد 2026: طلبها عبر بوابة مصر الرقمية"
};
