// Explicit editorial search titles; keep full descriptive H1s in the articles.
export const searchTitles: Record<string, string> = {
  "ration-family-join": "ضم الأسرة إلى بطاقة التموين: الشروط وخطوات الطلب",
  "old-rent-housing-post-office": "السكن البديل من مكتب البريد: المستندات والتقديم",
  "alexandria-electricity": "كهرباء الإسكندرية: الفاتورة وبلاغات الأعطال",
  "ration-data-update": "تحديث بيانات التموين: استخدام استمارة مصر الرقمية",
  "chrome-separate-profiles": "ملفات Chrome الشخصية: فصل العمل والدراسة",
  "drive-file-restore": "استعادة ملفات Google Drive المحذوفة وحدود الاسترداد",
  "chrome-update-check": "تحديث Chrome على الكمبيوتر وحل مشاكل التعثر",
  "ration-card-replacement": "بدل فاقد وتالف بطاقة التموين: الإيقاف وطلب البديل",
  "google-backup-codes": "رموز Google الاحتياطية: الإعداد واستخدامها للتحقق",
  "ration-card-activation": "تفعيل بطاقة التموين: الشروط وخطوات المتابعة",
  "south-cairo-electricity": "كهرباء جنوب القاهرة: الفواتير والسداد والشكاوى",
  "old-rent-housing-track": "متابعة طلب السكن البديل والنواقص والتظلم من الرفض",
  "chrome-cache-site-data": "مسح الكاش وبيانات الموقع في Chrome بأمان",
  "national-id-damaged-replacement": "بدل تالف بطاقة الرقم القومي: الطلب ومراجعة البيانات",
  "android-location-permissions": "إذن الموقع في Android: اختيار الدقة لكل تطبيق",
  "google-device-sessions": "أجهزة حساب Google: المراجعة وإخراج جهاز غريب",
  "chrome-bookmarks-transfer": "نقل إشارات Chrome: التصدير والاستيراد والتحقق",
  "south-delta-electricity": "فاتورة كهرباء جنوب الدلتا: الاستعلام والسداد",
  "android-usb-file-transfer": "نقل ملفات Android بكابل USB وحل مشاكل الاتصال",
  "north-delta-electricity": "كهرباء شمال الدلتا: الفاتورة والقراءة والشكاوى",
  "iphone-backup-choice": "نسخ iPhone احتياطيًا: iCloud أم الكمبيوتر؟",
  "north-cairo-electricity": "كهرباء شمال القاهرة: الفاتورة والقراءة والسداد",
  "android-privacy-dashboard": "لوحة خصوصية Android: مراجعة وصول التطبيقات",
  "national-id-lost-replacement": "بدل فاقد الرقم القومي عبر مصر الرقمية: خطوات الطلب",
  "google-data-download": "تنزيل بيانات Google: Takeout أم التنزيل المباشر؟",
  "gmail-filters": "فلاتر Gmail: تنظيم الرسائل دون فقد البريد المهم",
  "old-rent-housing-apply": "التسجيل في السكن البديل قبل 12 أكتوبر 2026",
  "old-rent-housing-documents": "مستندات السكن البديل: الإيجار والحالة والدخل",
  "chrome-crash-diagnosis": "Chrome لا يفتح أو يتعطل: تشخيص المشكلة وحلها",
  "old-rent-housing-eligibility": "شروط السكن البديل وكيف تُفحص أهلية الطلب",
  "lost-iphone-find-my": "فقدان iPhone: العثور عليه ونمط الفقدان وتجنب النصب"
};
